### ISSUE TITLE
Mots de passe !

### ISSUE THREAD

**Issue by Balsakup** [asuri0n/Projet_Web_Pluginmaker#1]
Des mots de passe sont restés ! Surtout celui du serveur SQL

Voici des commandes pour supprimer le fichier de tous les commits et réécrire l'historique
```bash
$ git filter-branch --index-filter "git rm -rf --cached --ignore-unmatch admin/.htpasswd includes/configuration.php" HEAD
$ rm -rf .git\refs\original\
$ git reflog expire --all && git gc --aggressive --prune
$ git push -f origin master
```

**Comment by asuri0n** [comment]
Yes, oui c'est vrai, mais de toute facon ces mot de passes ne sont plus les bons ;) 
Pour le htpasswd, c'est crypté non ? 
Mais oui je sais c'est pas très pro de laisser ca :) 

Merci, je vais garder ces lignes Git de coté

**Comment by Balsakup** [comment]
> ces mot de passes ne sont plus les bons

J'ai fais mon curieux .. Et ils fonctionnent très bien ..

Pour le htpasswd, même si c'est chiffré / hashé, faut éviter au maximum de laisser des mots de passe ;)

**Comment by asuri0n** [comment]
Ah... 😂
Effectivement c'est un problème alors... 
Haha merci ! 😉
